(()=>{'use strict';const $=id=>document.getElementById(id),m=window.MathWild;
function showRoman(){const parts=m.romanParts($('numberInput').value);$('result').textContent=parts?parts.map(p=>p.symbol).join(''):'Use a whole number from 1 to 3999.';$('romanSteps').textContent=parts?parts.map(p=>`${p.symbol} (${p.value})`).join(' + '):'No zero, fractions, negative numbers, or oversized input in this notation.';}
function readRoman(){const n=m.fromRoman($('romanInput').value);$('decimalResult').textContent=n===null?'Try a standard numeral, such as IV or XLIX.':String(n);$('decimalSteps').textContent=n===null?'This bench rejects forms such as IIII, IL, and IIV.':m.romanParts(n).map(p=>`${p.symbol} = ${p.value}`).join('; ');}
$('romanForm').addEventListener('submit',e=>{e.preventDefault();showRoman();});$('decimalForm').addEventListener('submit',e=>{e.preventDefault();readRoman();});
function outfit(){const n=m.integer($('outfit').value,1,3999);const box=$('outfitResult');box.replaceChildren();if(n===null){box.textContent='Choose a whole number from 1 to 3999.';return;}for(const [name,value] of [['Decimal',String(n)],['Roman',m.toRoman(n)],['Binary',n.toString(2)+'₂']]){const p=document.createElement('p'),b=document.createElement('strong');b.textContent=name+': ';p.append(b,value);box.append(p);}const digits=String(n),decimal=[...digits].map((d,i)=>`${d} × ${10**(digits.length-i-1)}`).join(' + ');const binary=[...n.toString(2)].map((d,i,a)=>`${d} × ${2**(a.length-i-1)}`).join(' + ');const p=document.createElement('p');p.textContent=`Decimal places: ${decimal}. Binary places: ${binary}. Both totals are ${n}.`;box.append(p);}
$('outfit').addEventListener('input',outfit);
const svgNS='http://www.w3.org/2000/svg';for(let h=1;h<=12;h++){const t=document.createElementNS(svgNS,'text'),a=h*Math.PI/6;t.setAttribute('x',130+Math.sin(a)*91);t.setAttribute('y',130-Math.cos(a)*91);t.textContent=m.toRoman(h);$('clockLabels').append(t);}
function moveClock(){const c=m.clock($('startHour').value,$('hours').value);if(!c){$('clockResult').textContent='Use a starting hour 1–12 and a whole number of hours from 0–1000.';$('clockFace').hidden=true;return;}$('clockFace').hidden=false;$('clockResult').textContent=`${$('startHour').value} + ${$('hours').value} = ${c.total}. Dividing ${c.total} by 12 gives ${c.turns} full groups and remainder ${c.remainder}. The clock shows ${c.hour} (${m.toRoman(c.hour)}). This records the clock position, not elapsed AM/PM time.`;const a=c.hour*Math.PI/6;$('clockHand').setAttribute('x2',130+Math.sin(a)*75);$('clockHand').setAttribute('y2',130-Math.cos(a)*75);$('clockFace').setAttribute('aria-label',`A clock showing ${c.hour} o'clock`);}
$('clockButton').addEventListener('click',moveClock);
function group(){const p=m.packs($('stickers').value,$('pencils').value);$('packPicture').replaceChildren();if(!p){$('groupResult').textContent='Choose whole numbers from 1 to 200 for both supplies.';return;}$('groupResult').textContent=`Possible pack counts: ${p.common.join(', ')}. Most equal packs: ${p.count}; each has ${p.stickers} stickers and ${p.pencils} pencils. Sticker factors: ${p.factorsA.join(', ')}. Pencil factors: ${p.factorsB.join(', ')}.`;for(let i=1;i<=Math.min(p.count,24);i++){const card=document.createElement('div');card.className='pack';const title=document.createElement('strong');title.textContent='Pack '+i;card.append(title,`${p.stickers} stickers · ${p.pencils} pencils`);$('packPicture').append(card);}if(p.count>24){const note=document.createElement('p');note.textContent=`Showing the first 24 of ${p.count} identical packs.`;$('packPicture').append(note);}}
$('groupButton').addEventListener('click',group);
function scale(){const p=m.recipe($('servings').value);$('recipeResult').textContent=p?`300 g ÷ 4 people = 75 g per person. For ${p.servings} people: 75 × ${p.servings} = ${p.grams} g of flour. Scale factor ${p.servings}/4 = ${p.factor}.`:'Choose a whole number of people from 1 to 40.';$('flourBar').style.width=p?p.servings/40*100+'%':'0%';}
$('recipeButton').addEventListener('click',scale);showRoman();readRoman();outfit();moveClock();group();scale();})();
